### ISSUE TITLE
Upload to Curseforge

### ISSUE THREAD

**Issue by chorbintime** [Ezzenix/ChatAnimation#9]
By uploading the mod to Curseforge, we'd be able to include it in our modpack, Prominence. The spike in downloads that comes with this would allow for more people to discover your mod. 

We can technically use the mod in the modpack anyway due to the license, but we'd like you to receive Curseforge Credits for your work, as opposed to adding it as a mod override.

**Comment by Ezzenix** [comment]
Hi it is uploaded on curseforge 👍 

https://www.curseforge.com/minecraft/mc-mods/chatanimation
